package com.bigbangcraft.regions.payment.api;

public enum LandPaymentFailure {
    INSUFFICIENT_BALANCE,
    TRANSIENT_ERROR,
    TIMEOUT,
    DATABASE_UNAVAILABLE,
    PROVIDER_STARTING,
    API_INCOMPATIBLE,
    INVALID_REQUEST,
    PLAYER_NOT_FOUND,
    PROVIDER_UNAVAILABLE,
    RESERVATION_EXPIRED,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_ACTIVE,
    ALREADY_CAPTURED,
    ALREADY_RELEASED,
    IDEMPOTENCY_CONFLICT,
    INVALID_AMOUNT,
    INVALID_LEASE,
    MAX_BALANCE_EXCEEDED,
    DATA_INTEGRITY_FAILURE,
    PERSISTENCE_FAILURE,
    SHUTTING_DOWN,
    EXECUTOR_SATURATED,
    UNKNOWN_ERROR
}
